# Generated by Django 4.2 on 2023-04-24 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eliminationtournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='position_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions_one', to='eliminationtournaments.position'),
        ),
        migrations.AddField(
            model_name='match',
            name='position_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions_two', to='eliminationtournaments.position'),
        ),
    ]
