# Generated by Django 4.2 on 2023-04-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eliminationtournaments', '0002_match_position_one_match_position_two'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='position',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='round',
            name='round_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='match_time',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='tournament',
            name='total_rounds',
            field=models.IntegerField(default=0),
        ),
    ]
