# Generated by Django 4.2 on 2023-04-24 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eliminationtournaments', '0003_match_disabled_position_order_round_round_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eliminationtournaments.player'),
        ),
    ]
