# Generated by Django 4.2 on 2023-06-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eliminationtournaments', '0005_alter_tournament_tournament_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='voted',
            field=models.BooleanField(default=False),
        ),
    ]
