# Generated by Django 4.2 on 2023-06-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eliminationtournaments', '0006_match_voted'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='bracket_index',
            field=models.IntegerField(default=0),
        ),
    ]
