# Generated by Django 4.2 on 2023-06-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eliminationtournaments', '0007_position_bracket_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='bracket_index',
            field=models.IntegerField(default=-1),
        ),
    ]
