# Generated by Django 4.2 on 2023-07-05 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eliminationtournaments', '0008_alter_position_bracket_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='next_position',
        ),
        migrations.AddField(
            model_name='position',
            name='left_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_left', to='eliminationtournaments.position'),
        ),
        migrations.AddField(
            model_name='position',
            name='right_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_right', to='eliminationtournaments.position'),
        ),
    ]
