# Generated by Django 4.2 on 2023-07-05 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eliminationtournaments', '0009_remove_position_next_position_position_left_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='left_position',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_left', to='eliminationtournaments.position'),
        ),
        migrations.AlterField(
            model_name='position',
            name='right_position',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_right', to='eliminationtournaments.position'),
        ),
    ]
