# Generated by Django 4.2 on 2023-07-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eliminationtournaments', '0012_rename_order_position_depth'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='end_match_time',
            field=models.IntegerField(default=0),
        ),
    ]
