# Generated by Django 4.2 on 2023-07-10 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eliminationtournaments', '0013_tournament_end_match_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='end_match_time',
            new_name='match_ends',
        ),
    ]
