# Generated by Django 4.2 on 2023-08-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eliminationtournaments', '0014_rename_end_match_time_tournament_match_ends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='match_ends',
            field=models.FloatField(default=0.0),
        ),
    ]
