# Generated by Django 4.2 on 2023-11-27 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eliminationtournaments', '0015_alter_tournament_match_ends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='tournament',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='Round',
        ),
    ]
