# Generated by Django 4.2 on 2023-12-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eliminationtournaments', '0016_remove_round_tournament_delete_match_delete_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
