# Generated by Django 4.2 on 2023-12-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eliminationtournaments', '0017_tournament_views'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['views'], name='elimination_views_e28d0a_idx'),
        ),
    ]
